### ISSUE TITLE
[QUESTION] How to get preferences from Android system package?

### ISSUE THREAD

**Issue by Firefds** [apsun/RemotePreferences#10]
I'm trying to load the preferences from the Android package but the preferences are not read for this package.
You can see the code here - https://github.com/Firefds/FirefdsKit/blob/pie_provider/firefdskit/src/main/java/sb/firefds/pie/firefdskit/XAndroidPackage.java
https://github.com/Firefds/FirefdsKit/blob/pie_provider/firefdskit/src/main/java/sb/firefds/pie/firefdskit/XSystemWide.java

Is this the same reason why we shouldn't use RemotePreferences from within IXposedHookZygoteInit.initZygote?

Is there a workaround for android packages?

**Comment by apsun** [comment]
Hm I looked at your commit https://github.com/Firefds/FirefdsKit/commit/93b5f8c59a473a18a2cfa668660fa259fea6c3c6 and it seems correct. Can you provide more info on what you mean by "preferences are not read"? You can try strict mode (pass an extra `true` argument to the `RemotePreferences` constructor) to get more information on why your code is failing, but be warned, it throws an exception on failure, so you'll want to catch and log it assuming your Xposed module is running system-wide.

**Comment by Firefds** [comment]
@apsun I attached the logs after activating strict mode -
[all.log](https://github.com/apsun/RemotePreferences/files/4236391/all.log)

Regarding the SystemWide class - once the system has completed the boot, the preferences for in this class are read.
The problem still remains with the XAndroidPackage class - the preferences file is returned empty

**Comment by apsun** [comment]
Ah, judging by the logs, it does appear that RemotePreferences doesn't work that early. I don't think there's a way to "fix" RemotePreferences (since it's dependent on ContentProvider/Resolver), however, if you want a workaround, you can always just read the preferences from within the hook callbacks instead of at package load; that should run late enough that you're able to break the dependency cycle.

**Comment by Firefds** [comment]
ok, moving the preferences inside the hook callbacks works for most cases.
In some hooks like [here](https://github.com/Firefds/FirefdsKit/blob/37e2cb5192646e131e91b89bd9640d3da53c3858/firefdskit/src/main/java/sb/firefds/pie/firefdskit/XAndroidPackage.java#L88) the system bootloops, probably because of a stackoverflow I keep getting, example here though not for this class, just so you get an idea - 

`java.lang.StackOverflowError: stack size 8MB
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at java.lang.StringBuffer.append(StringBuffer.java:367)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at java.io.StringWriter.write(StringWriter.java:94)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:380)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.android.internal.util.FastPrintWriter.appendLocked(FastPrintWriter.java:320)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.android.internal.util.FastPrintWriter.print(FastPrintWriter.java:497)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at java.io.PrintWriter.println(PrintWriter.java:756)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at java.lang.Throwable.printStackTrace(Throwable.java:651)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at java.lang.Throwable.printStackTrace(Throwable.java:713)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.util.Log.getStackTraceString(Log.java:472)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedBridge.log(XposedBridge.java:173)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:191)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ContextImpl.getClassLoader(ContextImpl.java:369)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6724)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6334)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2825)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1835)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.content.ContentResolver.query(ContentResolver.java:793)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.content.ContentResolver.query(ContentResolver.java:759)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.content.ContentResolver.query(ContentResolver.java:717)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:185)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:233)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:107)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at sb.firefds.pie.firefdskit.XSystemWide.doHook(XSystemWide.java:70)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at sb.firefds.pie.firefdskit.Xposed.handleLoadPackage(Xposed.java:76)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:68)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:130)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ContextImpl.getClassLoader(ContextImpl.java:369)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6724)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6334)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2825)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1835)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.content.ContentResolver.query(ContentResolver.java:793)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.content.ContentResolver.query(ContentResolver.java:759)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.content.ContentResolver.query(ContentResolver.java:717)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.crossbowffs.remotepreferences.RemotePreferences.query(RemotePreferences.java:185)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.crossbowffs.remotepreferences.RemotePreferences.querySingle(RemotePreferences.java:233)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.crossbowffs.remotepreferences.RemotePreferences.getBoolean(RemotePreferences.java:107)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at sb.firefds.pie.firefdskit.XSystemWide.doHook(XSystemWide.java:70)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at sb.firefds.pie.firefdskit.Xposed.handleLoadPackage(Xposed.java:76)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:68)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:130)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ContextImpl.getClassLoader(ContextImpl.java:369)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6724)
02-22 10:40:52.490  4391  4391 E EdXposed-Bridge: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6334)`

**Comment by apsun** [comment]
Glad to hear it works. The stacktrace you posted indicates that you are still calling RemotePreferences directly from the `handleLoadPackage` method instead of the hooked method callback.

**Comment by Firefds** [comment]
Oh right, that's because I'm trying to XposedHelpers.setStaticObjectField of a class that I'm not hooking into. I will try to see if I have a solution for that
