### ISSUE TITLE
Android 10 return default value

### ISSUE THREAD

**Issue by aldyjrz** [apsun/RemotePreferences#12]
Hello, apsun.
I have problem with my module that can't return new value in Android 10
Do you have any trick or tips to android 10?
It always return default value

**Comment by apsun** [comment]
As far as I know nothing inherent to Android 10 broke this (I've tested it to work fine on even Android 11). Try turning on strict mode (https://github.com/apsun/RemotePreferences#strict-mode), which will make it throw an exception instead of returning the default value. That way you can narrow down why it's failing.

**Comment by aldyjrz** [comment]
I appreciate for your fast response.
Thanks for your great work!!!
I'll try strict mode nexy

I'm Aldi, from Indonesia

**Comment by TkgJamuKeliling** [comment]
I have same problem here with Android 10. Value always return to default..

**Comment by aldyjrz** [comment]
> I have some problem here with Android 10. Value always return to default..

Just set preferences File to setReadable and Executable. 
And call it on every cycle like onResume, onPause, onRestart.

Wa aja sih lu gondrong

**Comment by TkgJamuKeliling** [comment]
> > I have some problem here with Android 10. Value always return to default..
> 
> Just set preferences File to setReadable and Executable.
> And call it on every cycle like onResume, onPause, onRestart.
> 
> Wa aja sih lu gondrong

oh begono... okelah... jajal dulu hu...

**Comment by aldyjrz** [comment]
> > > I have some problem here with Android 10. Value always return to default..
> > 
> > 
> > Just set preferences File to setReadable and Executable.
> > And call it on every cycle like onResume, onPause, onRestart.
> > Wa aja sih lu gondrong
> 
> oh begono... okelah... jajal dulu hu...

Japri dong mau nanya lagi masalah detector
0

**Comment by TkgJamuKeliling** [comment]
> > > > I have some problem here with Android 10. Value always return to default..
> > > 
> > > 
> > > Just set preferences File to setReadable and Executable.
> > > And call it on every cycle like onResume, onPause, onRestart.
> > > Wa aja sih lu gondrong
> > 
> > 
> > oh begono... okelah... jajal dulu hu...
> 
> Japri dong mau nanya lagi masalah detector
> 0

lupakan saja.. lebih baik simpan tenaga dan pikiran untuk GoPartner... :p

**Comment by StringInteger74** [comment]
> I have same problem here with Android 10. Value always return to default..

Try ....
setExecutable(true, false)
setReadable(true, false)
