### ISSUE TITLE
[Please Delete] Non-issue.

### ISSUE THREAD

**Issue by hahagu** [apsun/RemotePreferences#14]
Edit: Turns out my code was to blame
Sorry for the false alarm!
Thanks!

Please delete the issue :)

**Comment by apsun** [comment]
I have never actually used `getAll()` anyways, so I went to double check just in case. I added some unit tests for it regardless so I can point the finger at the user next time directly ;-) 092c9f64e93b354560f6c7f8a4b4151e52481cda

**Comment by hahagu** [comment]
:)
