### ISSUE TITLE
Is it Solve Xsharedpreference Can’t Access Preference XML

### ISSUE THREAD

**Issue by Android1500** [apsun/RemotePreferences#18]
As we knw after SDK 25 we other app can't access preference XML file I have a module which hook param which use put in my module and that data store in user_prefs.XML but my module easily get data in SDK less than 24 and can't access greater than 24 so ? Is it solve ?this

**Comment by apsun** [comment]
Yes, it's explicitly mentioned in the readme (https://github.com/apsun/RemotePreferences#why-would-i-need-this), this works on all Android versions including API25+.

**Comment by Android1500** [comment]
> Yes, it's explicitly mentioned in the readme (https://github.com/apsun/RemotePreferences#why-would-i-need-this), this works on all Android versions including API25+.

It's really sounds great by are uhh sure ? We can get preference.XML by  Xsharedpreference which store in data/user/packageName/preference.xml above SDK 25

**Comment by apsun** [comment]
I don't understand your question. You just claimed XSharedPreferences it doesn't work on API25, and now you're saying it does? If XSharedPreferences works for you, then by all means continue to use it.
