### ISSUE TITLE
[Question] How do I reload preferences?

### ISSUE THREAD

**Issue by Rijul-A** [apsun/RemotePreferences#2]
Similar to this link, http://api.xposed.info/reference/de/robv/android/xposed/XSharedPreferences.html#reload() how do I reload preferences when they change? 

Previously, using an onSharedPreferenceChangeListener has proved very unreliable for me but I did not get to diagnosing it at all.

Thanks for your help.

**Comment by apsun** [comment]
You shouldn't need to, every time you load a preference it will give you the newest value. RemotePreferences does not cache any data.

What is wrong with the listener? Did you make sure to maintain a strong reference to it? RemotePreferences follows the Android API in that you need to persist the reference yourself, or else it will be garbage collected.

**Comment by Rijul-A** [comment]
Hey - I want to thank you for this. I figured out how it works from QuoteLock source code. Maybe it would make sense this line to the tutorial? That is what I was missing
https://github.com/apsun/QuoteLock/blob/master/src/com/crossbowffs/quotelock/app/SettingsFragment.java#L38
