### ISSUE TITLE
multiple apps use the library but they have same authority for a content provider, which creates conflict

### ISSUE THREAD

**Issue by latifulmousom** [apsun/RemotePreferences#24]
I have created an android library that generates a random UUID when a user launches an app integrated with this library. If a user already has the UUID, we store it in sharedpref.
Now I want to access the UUID to other apps that are integrated with my library.(within the same device). I don't want to create a new random UUID for every app on the same device.

Can you help me to solve it? @apsun

**Comment by apsun** [comment]
RemotePreferences operates in a client-server model where one app is the "server" (the one exporting the provider) and clients (using `RemotePreferences`) talk to it. There is no way to have multiple apps export a provider on the same authority, as far as I know.

It sounds like you're trying to do something like an advertising tracking ID? Have you read the developer documentation on how to do this using the appropriate libraries, which are better suited to this usecase? https://developer.android.com/training/articles/user-data-ids
