### ISSUE TITLE
getting context in handleLoadPackage

### ISSUE THREAD

**Issue by MPeti1** [apsun/RemotePreferences#3]
Hi!
You wrote we should load preferences in IXposedHookLoadPackage.handleLoadPackage. But how do one get a context here? AndroidAppHelper.currentApplication().getApplicationContext() will return null since there is no context before handleBindApplication(), because it'll be set up in it.

**Comment by apsun** [comment]
Hmm, I'm not that familiar with Xposed actually, that advice might be outdated or flat out wrong. Would it be feasible to hook handleBindApplication instead and load your preferences then, instead of handleLoadPackage?

**Comment by MPeti1** [comment]
Yes, it's a good idea, but that makes the code uglier :/ what I'm trying now is creating a context myself with the content resolver loaded

**Comment by MPeti1** [comment]
It seems I've found a solution!
System context is available before handleLoadPackage(), so you can use this for constructing a RemotePreferences. I've not tested yet what is the difference on the content provider side, for example if getCallingPackage() returns the real calling package or just "android", but basically it's working, so whatever is the case, you can use this at the very beginning.

Here is how I obtain the system context:
`Context systemContext = (Context) XposedHelpers.callMethod(
                XposedHelpers.callStaticMethod(
                        XposedHelpers.findClass("android.app.ActivityThread", loadPackageParam.classLoader),
                        "currentActivityThread"),
                "getSystemContext"
        );`

**Comment by Palatis** [comment]
> 
> 
> It seems I've found a solution!
> System context is available before handleLoadPackage(), so you can use this for constructing a RemotePreferences. I've not tested yet what is the difference on the content provider side, for example if getCallingPackage() returns the real calling package or just "android", but basically it's working, so whatever is the case, you can use this at the very beginning.
> 
> Here is how I obtain the system context:
> `Context systemContext = (Context) XposedHelpers.callMethod( XposedHelpers.callStaticMethod( XposedHelpers.findClass("android.app.ActivityThread", loadPackageParam.classLoader), "currentActivityThread"), "getSystemContext" );`

this one should be on `readme.md`...
